# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection1
    - task: Docker@2
      displayName: Build an image and push it to Azure Repository Container
      inputs:
        command: buildAndPush
        dockerfile: '**/Dockerfile'
        repository acoragrafana
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: dockerRegistryServiceConnection1